//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/InputActions/RikschaControll.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @RikschaControll: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @RikschaControll()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""RikschaControll"",
    ""maps"": [
        {
            ""name"": ""Menu"",
            ""id"": ""febddbaf-3fc4-44da-8a5e-ed2cb26f5042"",
            ""actions"": [
                {
                    ""name"": ""SubmitScore"",
                    ""type"": ""Button"",
                    ""id"": ""daa3bd73-85f8-4b73-904d-81f94b07f3e2"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""14764ed0-d1c2-4267-9322-047052147d89"",
                    ""path"": ""<Keyboard>/enter"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""SubmitScore"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""InGame"",
            ""id"": ""335fb0d3-a7f0-40b6-ba12-e6f7c35619d8"",
            ""actions"": [
                {
                    ""name"": ""RikschaMoveHorizontal"",
                    ""type"": ""Value"",
                    ""id"": ""97b04dd5-4729-4e6c-9b6f-0408e51e483b"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""BowlRotationX"",
                    ""type"": ""Value"",
                    ""id"": ""f43c41a7-d4b4-4333-9710-5dcfc8c258b2"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""TurboRotation"",
                    ""type"": ""Button"",
                    ""id"": ""b6c69b24-bb2e-48aa-9922-71396aa4e522"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""PauseGame"",
                    ""type"": ""Button"",
                    ""id"": ""829940ba-d9bb-4026-a26c-1d96c077a8f3"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""BowlRotationXMouse"",
                    ""type"": ""Value"",
                    ""id"": ""16d4ee2c-7c41-4879-9b40-23510a4c2281"",
                    ""expectedControlType"": ""Axis"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""7ec36c16-5317-441d-9dde-4bfa3577dfdb"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RikschaMoveHorizontal"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""dacdce31-d930-42f3-b1e7-f3f2dc5af9d9"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RikschaMoveHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""b38d3767-8e2d-4295-a4b1-ac81fb2be737"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RikschaMoveHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""bdfd44fb-1924-4702-9b36-88a50e49fe80"",
                    ""path"": ""<Gamepad>/leftStick/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RikschaMoveHorizontal"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b7795514-8c9d-4152-8000-b0e38425728c"",
                    ""path"": ""<Gamepad>/rightStick/x"",
                    ""interactions"": """",
                    ""processors"": ""Scale(factor=10)"",
                    ""groups"": """",
                    ""action"": ""BowlRotationX"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""42ee15db-3d9a-4f73-b6cc-198b7a529693"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TurboRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""4ae3fcdc-71aa-4ba8-b96a-db8d6d452b2b"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TurboRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""19cbfdef-cd6c-4fd1-a3fa-c28a0decae7f"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TurboRotation"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""9707128e-b725-448c-83bc-d0dc5b04e7e2"",
                    ""path"": ""<Keyboard>/escape"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b24dd85d-5407-4b7a-9d53-df455cced68b"",
                    ""path"": ""<Gamepad>/start"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""PauseGame"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""8cf72357-ac2a-49c5-a7bf-f87d18044fe0"",
                    ""path"": ""<Mouse>/delta/x"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""BowlRotationXMouse"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        },
        {
            ""name"": ""PauseMenu"",
            ""id"": ""73e8272c-6957-4192-b332-156b48f70a1a"",
            ""actions"": [
                {
                    ""name"": ""Umpause"",
                    ""type"": ""Button"",
                    ""id"": ""e16a943a-6f94-449c-ac42-d0abac4bc177"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Navigate"",
                    ""type"": ""Button"",
                    ""id"": ""33c82ee9-612c-49b4-9cc1-500b2a2b15a9"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Select"",
                    ""type"": ""Button"",
                    ""id"": ""9c680a7f-0792-43db-ab1d-c7e10f9cb96b"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""74a06f50-2803-4c11-9967-01a54f4837ce"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Umpause"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""04a33983-20d6-426c-a064-fe6662d3f2ea"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Navigate"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""96826a7e-7985-4493-80d2-79907c7100b9"",
                    ""path"": """",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Select"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Menu
        m_Menu = asset.FindActionMap("Menu", throwIfNotFound: true);
        m_Menu_SubmitScore = m_Menu.FindAction("SubmitScore", throwIfNotFound: true);
        // InGame
        m_InGame = asset.FindActionMap("InGame", throwIfNotFound: true);
        m_InGame_RikschaMoveHorizontal = m_InGame.FindAction("RikschaMoveHorizontal", throwIfNotFound: true);
        m_InGame_BowlRotationX = m_InGame.FindAction("BowlRotationX", throwIfNotFound: true);
        m_InGame_TurboRotation = m_InGame.FindAction("TurboRotation", throwIfNotFound: true);
        m_InGame_PauseGame = m_InGame.FindAction("PauseGame", throwIfNotFound: true);
        m_InGame_BowlRotationXMouse = m_InGame.FindAction("BowlRotationXMouse", throwIfNotFound: true);
        // PauseMenu
        m_PauseMenu = asset.FindActionMap("PauseMenu", throwIfNotFound: true);
        m_PauseMenu_Umpause = m_PauseMenu.FindAction("Umpause", throwIfNotFound: true);
        m_PauseMenu_Navigate = m_PauseMenu.FindAction("Navigate", throwIfNotFound: true);
        m_PauseMenu_Select = m_PauseMenu.FindAction("Select", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Menu
    private readonly InputActionMap m_Menu;
    private List<IMenuActions> m_MenuActionsCallbackInterfaces = new List<IMenuActions>();
    private readonly InputAction m_Menu_SubmitScore;
    public struct MenuActions
    {
        private @RikschaControll m_Wrapper;
        public MenuActions(@RikschaControll wrapper) { m_Wrapper = wrapper; }
        public InputAction @SubmitScore => m_Wrapper.m_Menu_SubmitScore;
        public InputActionMap Get() { return m_Wrapper.m_Menu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(MenuActions set) { return set.Get(); }
        public void AddCallbacks(IMenuActions instance)
        {
            if (instance == null || m_Wrapper.m_MenuActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_MenuActionsCallbackInterfaces.Add(instance);
            @SubmitScore.started += instance.OnSubmitScore;
            @SubmitScore.performed += instance.OnSubmitScore;
            @SubmitScore.canceled += instance.OnSubmitScore;
        }

        private void UnregisterCallbacks(IMenuActions instance)
        {
            @SubmitScore.started -= instance.OnSubmitScore;
            @SubmitScore.performed -= instance.OnSubmitScore;
            @SubmitScore.canceled -= instance.OnSubmitScore;
        }

        public void RemoveCallbacks(IMenuActions instance)
        {
            if (m_Wrapper.m_MenuActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IMenuActions instance)
        {
            foreach (var item in m_Wrapper.m_MenuActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_MenuActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public MenuActions @Menu => new MenuActions(this);

    // InGame
    private readonly InputActionMap m_InGame;
    private List<IInGameActions> m_InGameActionsCallbackInterfaces = new List<IInGameActions>();
    private readonly InputAction m_InGame_RikschaMoveHorizontal;
    private readonly InputAction m_InGame_BowlRotationX;
    private readonly InputAction m_InGame_TurboRotation;
    private readonly InputAction m_InGame_PauseGame;
    private readonly InputAction m_InGame_BowlRotationXMouse;
    public struct InGameActions
    {
        private @RikschaControll m_Wrapper;
        public InGameActions(@RikschaControll wrapper) { m_Wrapper = wrapper; }
        public InputAction @RikschaMoveHorizontal => m_Wrapper.m_InGame_RikschaMoveHorizontal;
        public InputAction @BowlRotationX => m_Wrapper.m_InGame_BowlRotationX;
        public InputAction @TurboRotation => m_Wrapper.m_InGame_TurboRotation;
        public InputAction @PauseGame => m_Wrapper.m_InGame_PauseGame;
        public InputAction @BowlRotationXMouse => m_Wrapper.m_InGame_BowlRotationXMouse;
        public InputActionMap Get() { return m_Wrapper.m_InGame; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(InGameActions set) { return set.Get(); }
        public void AddCallbacks(IInGameActions instance)
        {
            if (instance == null || m_Wrapper.m_InGameActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_InGameActionsCallbackInterfaces.Add(instance);
            @RikschaMoveHorizontal.started += instance.OnRikschaMoveHorizontal;
            @RikschaMoveHorizontal.performed += instance.OnRikschaMoveHorizontal;
            @RikschaMoveHorizontal.canceled += instance.OnRikschaMoveHorizontal;
            @BowlRotationX.started += instance.OnBowlRotationX;
            @BowlRotationX.performed += instance.OnBowlRotationX;
            @BowlRotationX.canceled += instance.OnBowlRotationX;
            @TurboRotation.started += instance.OnTurboRotation;
            @TurboRotation.performed += instance.OnTurboRotation;
            @TurboRotation.canceled += instance.OnTurboRotation;
            @PauseGame.started += instance.OnPauseGame;
            @PauseGame.performed += instance.OnPauseGame;
            @PauseGame.canceled += instance.OnPauseGame;
            @BowlRotationXMouse.started += instance.OnBowlRotationXMouse;
            @BowlRotationXMouse.performed += instance.OnBowlRotationXMouse;
            @BowlRotationXMouse.canceled += instance.OnBowlRotationXMouse;
        }

        private void UnregisterCallbacks(IInGameActions instance)
        {
            @RikschaMoveHorizontal.started -= instance.OnRikschaMoveHorizontal;
            @RikschaMoveHorizontal.performed -= instance.OnRikschaMoveHorizontal;
            @RikschaMoveHorizontal.canceled -= instance.OnRikschaMoveHorizontal;
            @BowlRotationX.started -= instance.OnBowlRotationX;
            @BowlRotationX.performed -= instance.OnBowlRotationX;
            @BowlRotationX.canceled -= instance.OnBowlRotationX;
            @TurboRotation.started -= instance.OnTurboRotation;
            @TurboRotation.performed -= instance.OnTurboRotation;
            @TurboRotation.canceled -= instance.OnTurboRotation;
            @PauseGame.started -= instance.OnPauseGame;
            @PauseGame.performed -= instance.OnPauseGame;
            @PauseGame.canceled -= instance.OnPauseGame;
            @BowlRotationXMouse.started -= instance.OnBowlRotationXMouse;
            @BowlRotationXMouse.performed -= instance.OnBowlRotationXMouse;
            @BowlRotationXMouse.canceled -= instance.OnBowlRotationXMouse;
        }

        public void RemoveCallbacks(IInGameActions instance)
        {
            if (m_Wrapper.m_InGameActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IInGameActions instance)
        {
            foreach (var item in m_Wrapper.m_InGameActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_InGameActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public InGameActions @InGame => new InGameActions(this);

    // PauseMenu
    private readonly InputActionMap m_PauseMenu;
    private List<IPauseMenuActions> m_PauseMenuActionsCallbackInterfaces = new List<IPauseMenuActions>();
    private readonly InputAction m_PauseMenu_Umpause;
    private readonly InputAction m_PauseMenu_Navigate;
    private readonly InputAction m_PauseMenu_Select;
    public struct PauseMenuActions
    {
        private @RikschaControll m_Wrapper;
        public PauseMenuActions(@RikschaControll wrapper) { m_Wrapper = wrapper; }
        public InputAction @Umpause => m_Wrapper.m_PauseMenu_Umpause;
        public InputAction @Navigate => m_Wrapper.m_PauseMenu_Navigate;
        public InputAction @Select => m_Wrapper.m_PauseMenu_Select;
        public InputActionMap Get() { return m_Wrapper.m_PauseMenu; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(PauseMenuActions set) { return set.Get(); }
        public void AddCallbacks(IPauseMenuActions instance)
        {
            if (instance == null || m_Wrapper.m_PauseMenuActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PauseMenuActionsCallbackInterfaces.Add(instance);
            @Umpause.started += instance.OnUmpause;
            @Umpause.performed += instance.OnUmpause;
            @Umpause.canceled += instance.OnUmpause;
            @Navigate.started += instance.OnNavigate;
            @Navigate.performed += instance.OnNavigate;
            @Navigate.canceled += instance.OnNavigate;
            @Select.started += instance.OnSelect;
            @Select.performed += instance.OnSelect;
            @Select.canceled += instance.OnSelect;
        }

        private void UnregisterCallbacks(IPauseMenuActions instance)
        {
            @Umpause.started -= instance.OnUmpause;
            @Umpause.performed -= instance.OnUmpause;
            @Umpause.canceled -= instance.OnUmpause;
            @Navigate.started -= instance.OnNavigate;
            @Navigate.performed -= instance.OnNavigate;
            @Navigate.canceled -= instance.OnNavigate;
            @Select.started -= instance.OnSelect;
            @Select.performed -= instance.OnSelect;
            @Select.canceled -= instance.OnSelect;
        }

        public void RemoveCallbacks(IPauseMenuActions instance)
        {
            if (m_Wrapper.m_PauseMenuActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IPauseMenuActions instance)
        {
            foreach (var item in m_Wrapper.m_PauseMenuActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PauseMenuActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public PauseMenuActions @PauseMenu => new PauseMenuActions(this);
    public interface IMenuActions
    {
        void OnSubmitScore(InputAction.CallbackContext context);
    }
    public interface IInGameActions
    {
        void OnRikschaMoveHorizontal(InputAction.CallbackContext context);
        void OnBowlRotationX(InputAction.CallbackContext context);
        void OnTurboRotation(InputAction.CallbackContext context);
        void OnPauseGame(InputAction.CallbackContext context);
        void OnBowlRotationXMouse(InputAction.CallbackContext context);
    }
    public interface IPauseMenuActions
    {
        void OnUmpause(InputAction.CallbackContext context);
        void OnNavigate(InputAction.CallbackContext context);
        void OnSelect(InputAction.CallbackContext context);
    }
}
